----------
-- SCRIPTS PARA TABELA DE MARCAS
----------

CREATE TABLE tb_marca (
    id_marca 		NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome_marca  	VARCHAR2(256)
);


INSERT INTO tb_marca (nome_marca) VALUES ('HP');
INSERT INTO tb_marca (nome_marca) VALUES ('Apple');
INSERT INTO tb_marca (nome_marca) VALUES ('LG');
INSERT INTO tb_marca (nome_marca) VALUES ('Lenovo');

SELECT * FROM TB_MARCA;
-- APAGA VERSOES ANTERIORES SE EXISTIR
DROP TABLE tb_produto;

-- CRIA TABELA DE PRODUTOS
CREATE TABLE tb_produto (
    id               NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome             VARCHAR2(256),
    sku              VARCHAR2(256),
    descricao        VARCHAR2(256),
    caracteristicas  VARCHAR2(256),
    preco            NUMBER(10, 2),
    id_categoria     NUMBER(10) NOT NULL,
    id_marca		 NUMBER(10) NOT NULL,
    CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES tb_categoria(id_categoria),
    CONSTRAINT FK_ID_MARCA FOREIGN KEY (id_marca) REFERENCES tb_marca(id_marca)
);



-- INSERE VALORES DE TESTE
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 1', 'sku-0001', 'DescriÃ§Ã£o do Produto 1', 'CaracterÃ­sticas do produto 1', 1.99, 1, 1);
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 2', 'sku-0002', 'DescriÃ§Ã£o do Produto 2', 'CaracterÃ­sticas do produto 2', 2.99, 2, 2);
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 3', 'sku-0003', 'DescriÃ§Ã£o do Produto 3', 'CaracterÃ­sticas do produto 3', 3.99, 3, 3);
INSERT INTO TB_PRODUTO (NOME, SKU, DESCRICAO, CARACTERISTICAS, PRECO, ID_CATEGORIA, ID_MARCA) VALUES ('Nome do produto 4', 'sku-0004', 'DescriÃ§Ã£o do Produto 4', 'CaracterÃ­sticas do produto 4', 4.99, 4, 2);

COMMIT;

SELECT P.ID, P.NOME, P.SKU, P.DESCRICAO, P.CARACTERISTICAS, P.PRECO, P.ID_CATEGORIA, C.NOME_CATEGORIA, P.ID_MARCA, M.NOME_MARCA
FROM TB_PRODUTO P 
INNER JOIN TB_CATEGORIA C
ON P.ID_CATEGORIA = C.ID_CATEGORIA 
INNER JOIN TB_MARCA M 
ON P.ID_MARCA = M.ID_MARCA
;